-- USE jikfarm_db;

-- ALTER TABLE fact_trade_weekly ADD COLUMN year_part INT 
--   GENERATED ALWAYS AS (CAST(LEFT(weekno, 4) AS UNSIGNED)) STORED;

-- ALTER TABLE fact_trade ADD COLUMN year_part INT 
--  GENERATED ALWAYS AS (CAST(YEAR(trd_clcln_ymd) AS UNSIGNED)) STORED;

-- ALTER TABLE fact_trade_weekly DROP FOREIGN KEY fact_trade_weekly_ibfk_1;
-- ALTER TABLE fact_trade DROP FOREIGN KEY fact_trade_ibfk_1;

ALTER TABLE fact_trade_weekly DROP PRIMARY KEY, 
	ADD PRIMARY KEY (year_part, weekno, crop_full_code, j_sanji_cd);
ALTER TABLE fact_trade DROP PRIMARY KEY, 
	ADD PRIMARY KEY (year_part, trd_clcln_ymd, crop_full_code, j_sanji_cd);


ALTER TABLE fact_trade_weekly
PARTITION BY RANGE (year_part) (
  PARTITION p2018 VALUES LESS THAN (2019),
  PARTITION p2019 VALUES LESS THAN (2020),
  PARTITION p2020 VALUES LESS THAN (2021),
  PARTITION p2021 VALUES LESS THAN (2022),
  PARTITION p2022 VALUES LESS THAN (2023),
  PARTITION p2023 VALUES LESS THAN (2024),
  PARTITION p2024 VALUES LESS THAN (2025),
  PARTITION p2025 VALUES LESS THAN (2026),
  PARTITION pMAX VALUES LESS THAN MAXVALUE
);

ALTER TABLE fact_trade
PARTITION BY RANGE (year_part) (
  PARTITION p2018 VALUES LESS THAN (2019),
  PARTITION p2019 VALUES LESS THAN (2020),
  PARTITION p2020 VALUES LESS THAN (2021),
  PARTITION p2021 VALUES LESS THAN (2022),
  PARTITION p2022 VALUES LESS THAN (2023),
  PARTITION p2023 VALUES LESS THAN (2024),
  PARTITION p2024 VALUES LESS THAN (2025),
  PARTITION p2025 VALUES LESS THAN (2026),
  PARTITION pMAX VALUES LESS THAN MAXVALUE
);